site_name: ProblemCon++ 2.0 hackahon workshop - NN basics with TensorFlow
theme:
  name: material
  theme:
    logo: logo.png
    icon:
      repo: fontawesome/brands/github
    palette:

      # Palette toggle for light mode
      - media: "(prefers-color-scheme: light)"
        scheme: default
        toggle:
          icon: material/toggle-switch
          name: Switch to dark mode

      # Palette toggle for dark mode
      - media: "(prefers-color-scheme: dark)"
        scheme: slate
        toggle:
          icon: material/toggle-switch-off-outline
          name: Switch to light mode
#nav:
  #- Notebook page: index.ipynb
hide:
  - navigation

repo_url: https://github.com/fulcrum101/Problemcon_hackathon_TensorFlow

extra:
  homepage: https://www.problemcon.lv

plugins:
  - search
  - mkdocs-jupyter:
      theme: chesterish