site_name: ProblemCon++ 2.0 hackahon workshop - NN basics with TensorFlow
theme:
  name: material
  palette:
    scheme: slate
  logo: logo.png
nav:
  - Notebook page: index.ipynb

plugins:
  - search
  - mkdocs-jupyter:
      theme: chesterish